version: "3"
services:
  webapp:
    build:
      context: ./src
    ports:
      - "12003:3000"
    environment:
      - FLAG=USCG{REDACTED}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
